MODEL:
  TYPE: ssd_mobilenetv3
  SIZE: '512'
  REFINE: False
  CONV_BODY: mobilenetv3_new.SSDMobilenetv3
  NUM_CLASSES: 5
  LOAD_PRETRAINED_WEIGHTS: False
  PRETRAIN_WEIGHTS: './weights/pretrained_models/ssd_mobilenet_v3_large.pth'

TRAIN:
  OVERLAP: 0.5
  BGR_MEAN: [104, 117, 123]
  BATCH_SIZE: 128
  OHEM: True
  NEG_RATIO: 3
  WARMUP: True
  WARMUP_EPOCH: 2
  TRAIN_ON: True


SMALL:
  FEATURE_MAPS: [[19, 19], [10, 10], [5, 5], [3, 3], [2, 2], [1, 1]]
  ARM_CHANNELS: [672, 960, 256, 256, 256, 256]
  NUM_ANCHORS: [4, 6, 6, 6, 4, 4]
  STEPS: [[16, 16], [32, 32], [64, 64], [100, 100], [150, 150], [300, 300]]
  MIN_SIZES: [60, 105, 150, 195, 240, 285]
  MAX_SIZES: [105, 150, 195, 240, 285, 330]
  ASPECT_RATIOS : [[2, 0.5], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 0.5], [2, 0.5]]
  VARIANCE : [0.1, 0.2]
  CLIP: True
  IMG_WH: [300, 300]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: True

BIG:
  FEATURE_MAPS: [[32, 32], [16, 16], [8, 8], [4, 4], [2, 2], [1, 1]]
  ARM_CHANNELS: [672, 960, 512, 512, 256, 256] # mobilenetv3 Arm_Channels
  NUM_ANCHORS: [4, 6, 6, 6, 4, 4]
  STEPS: [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256], [512, 512]]
  MIN_SIZES: [51.2, 102.4, 189.4, 276.4, 363.52, 450.6]
  MAX_SIZES: [102.4, 189.4, 276.4, 363.52, 450.6, 492]
  ASPECT_RATIOS : [[2, 0.5], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 3, 0.5, 0.333], [2, 0.5], [2, 0.5]]
  CLIP: True
  IMG_WH: [512, 512]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: True

SOLVER:
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.005
  GAMMA: 0.1
  MOMENTUM: 0.9
  EPOCH_STEPS: [0, 150, 200]
  END_EPOCH: 250
  START_EPOCH: 0

DATASETS:
  TRAIN_TYPE: [['7.13', 'train']]
  VAL_TYPE: [['7.13', 'test']]
  DATAROOT: '/data/syy/data/mozi/new/'
  DATA_TYPE: 'CHECKOUT'
  SETS:
    VOC: [['0712', '0712_trainval']]
    VOC0712PLUS: [['0712', '0712_trainval_test']]
    VOC0712: [['2012', '2012_trainval']]
    COCO: [['2014', 'train'], ['2014', 'valminusminival']]
    VOC2007: [['0712', "2007_test"]]
    COCOval: [['2014', 'minival']]
    VOCROOT: 'data/datasets/VOCdevkit0712/'
    COCOROOT: 'data/datasets/coco2015'
  
TEST:
  INPUT_WH: [512, 512]
  CONFIDENCE_THRESH: 0.01
  NMS_OVERLAP: 0.45
  BATCH_SIZE: 16
  




